#! /bin/bash
set -e

<?py if conflicts.files: ?>
files="
<?py    for f in conflicts.files: ?>
<?py        if f.type() == "file": ?>
#{f.original_path}
<?py        #endif ?>
<?py    #endfor ?>
"

for f in $files
do
    dest=#{conflicts.savedir}$f
    new=#{conflicts.newdir}$f

    dir=$(dirname $dest)
    test -d $dir || mkdir -p $dir

    # 1. save original file:
    if test -f $dest; then
        csum1=$(sha1sum $f | cut -f 1 -d ' ')
        csum2=$(sha1sum $dest | cut -f 1 -d ' ')

        if test "x$csum1" = "x$csum2"; then
            echo "[Info] Looks already saved. Skip it: $f"
        else
            echo "[Info] Overwrite priviously saved one: $f"
            cp -af $f $dest
        fi
    else
        echo "[Info] Saving: $f"
        cp -a $f $dest
    fi

    # 2. install new one:
    echo "[Info] Overwrite $f with $new"
    cp --no-preserve=all $new $f
done
<?py else: ?>
# No conflicts and nothing to do:
exit 0
<?py #endif ?>
