#! /bin/bash
set -e

<?py if conflicts.files: ?>
files="
<?py    for f in conflicts.files: ?>
<?py        if f.type() == "file": ?>
#{f.original_path}
<?py        #endif ?>
<?py    #endfor ?>
"

for f in $files
do
    backup=#{conflicts.savedir}$f

    csum1=$(sha1sum $f | cut -f 1 -d ' ')
    csum2=$(sha1sum $backup | cut -f 1 -d ' ')

    if test "x$csum1" = "x$csum2"; then
        echo "[Info] Looks already backed up. Skip it: $f"
    else
        echo "[Info] Restore from backup: $f"
        cp -af $backup $f
    fi
done
<?py else: ?>
# No conflicts and nothing to do:
exit 0
<?py #endif ?>
