#! /bin/bash
#
# TODO: It may need to be run as root.
#
#set -e

domain_name=${domain.name}
domain_xml=${domain.xml_path}

#raw
virsh=$(which virsh)
test $(id -u) = "0" && virsh=$virsh || virsh="sudo $virsh"

if test -x /sbin/service; then
    libvirtd_check="/sbin/service libvirtd status"
elif test -x /etc/init.d/libvirtd; then
    libvirtd_check="/etc/init.d/libvirtd status"
else
    libvirtd_check="/etc/rc.d/libvirtd status"
fi

$libvirtd_check 2>&1 > /dev/null; rc=$?

if test $rc != 0; then  # libvirtd is not running.
    rm -f /etc/libvirt/qemu/${dmain_name}.xml
    exit 0
fi

if $($virsh list | grep -q ${domain_name} 2>/dev/null); then
    echo "${domain_name} is running now. Updates will be applied later."
fi

echo "[Info] De-registering: ${domain_name}"
$virsh undefine ${domain_name}
#end raw
# vim: set sw=4 ts=4 et:
