#! /bin/bash
#
# TODO: It may need to be run as root.
#
#set -e

domain_name=${domain.name}
domain_xml=${domain.xml_path}

#raw
virsh=$(which virsh)
test $(id -u) = "0" && virsh=$virsh || virsh="sudo $virsh"

if test -x /sbin/service; then
    libvirtd_check="/sbin/service libvirtd status"
elif test -x /etc/init.d/libvirtd; then
    libvirtd_check="/etc/init.d/libvirtd status"
else
    libvirtd_check="/etc/rc.d/libvirtd status"
fi

$libvirtd_check 2>&1 > /dev/null; rc=$?

if test $rc != 0; then  # libvirtd is not running.
    install -m 600 ${domain_xml} /etc/libvirt/qemu/
    exit 0
fi

if $($virsh list | grep -q ${domain_name} 2>/dev/null); then
    cat << EOF
${domain_name} is running now. Updates will be applied later.
EOF
    # FIXME: Is it needed to undefine the old one and define the new one?
    install -m 600 ${domain_xml} /etc/libvirt/qemu/
    exit 0
fi

if $($virsh list --all | grep -q ${domain_name} 2>/dev/null); then
    echo "[Info] De-registering the old: ${domain_name}"
    $virsh undefine ${domain_name}
fi

echo "[Info] Registering: ${domain_name}"
$virsh define ${domain_xml}

#end raw
# vim: set sw=4 ts=4 et:
