#! /bin/bash
set -e
{% if conflicts.files %}
files="
{%    for f in conflicts.files if f.filetype == 'file' %}{{ f.original_path }}
{%    endfor %}
"

for f in $files
do
    backup={{ conflicts.savedir }}$f

    csum1=$(sha1sum $f | cut -f 1 -d ' ')
    csum2=$(sha1sum $backup | cut -f 1 -d ' ')

    if test "x$csum1" = "x$csum2"; then
        echo "[Info] Looks already backed up. Skip it: $f"
    else
        echo "[Info] Restore from backup: $f"
        cp -af $backup $f
    fi
done
{% else %}
# No conflicts and nothing to do:
exit 0
{% endif %}
