#!/bin/sh
#
# see: dh_installdeb(1)
#
set -e

case "\$1" in
    remove|upgrade|deconfigure)
        /usr/libexec/${name}/register-domain
    ;;

    failed-upgrade)
    ;;

    *)
        echo "postrm called with unknown argument \`\$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
